
name: Build Homebrew

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkita64_devkitarm
    steps:
    - uses: actions/checkout@v1
    - name: Update repo.
      run: |
        git submodule update --init --recursive
        
    - name: Install devkitpro
      run: |
        wget https://github.com/devkitPro/pacman/releases/download/v1.0.2/devkitpro-pacman.amd64.deb
        sudo dpkg -i devkitpro-pacman.amd64.deb
        sudo dkp-pacman -S $(dkp-pacman -Ssq switch-*) --noconfirm
        
    - name: Make app
      run: |
        echo ##########################
        echo #     SETTING PATH       #
        echo ##########################
        echo
        export DEVKITPRO=/opt/devkitpro
        export DEVKITARM=${DEVKITPRO}/devkitARM
        export DEVKITPPC=${DEVKITPRO}/devkitPPC
        export PATH=${DEVKITPRO}/tools/bin:$PATH
        make
        
    - uses: actions/upload-artifact@master
      with:
        name: Build
        path: Haku33.nro
